services:
  - type: web
    name: biosync-backend
    env: python
    rootDir: Backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GEMINI_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false

